jobs:
  build:
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java_version }}
        server-id: sonatype-nexus-snapshots
        server-password: CI_DEPLOY_PASSWORD
        server-username: CI_DEPLOY_USERNAME
    - continue-on-error: true
      name: Build
      run: ./mvnw -V -B -ff -ntp verify
    - continue-on-error: true
      id: projectVersion
      name: Extract project Maven version
      run: echo "version=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.3.0:evaluate
        -DforceStdout -Dexpression=project.version -q)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      env:
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
      if: github.event_name != 'pull_request' && matrix.java_version == '8' && endsWith(steps.projectVersion.outputs.version,
        '-SNAPSHOT')
      name: Deploy snapshot
      run: ./mvnw -B -ff -DskipTests -ntp source:jar deploy
    strategy:
      fail-fast: false
      matrix:
        java_version:
        - '8'
        - '11'
        os:
        - ubuntu-20.04
name: Build and Deploy Snapshot
on:
  repository_dispatch:
    types: trigger-ga___main.yml
permissions:
  contents: read
